//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace Kedge.ws.EngineerERPWebExt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EngineerERPWebSoapBinding", Namespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
    public partial class EngineerERPWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback doStartOperationCompleted;
        
        private System.Threading.SendOrPostCallback doStopOperationCompleted;
        
        private System.Threading.SendOrPostCallback doCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTravleFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTravleAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEngTravleAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback openEngTravleAPEFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback openAPEFormOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EngineerERPWebService() {
            this.Url = global::Kedge.ws.Properties.Settings.Default.KedgeWebService_EngineerERPWebExt_EngineerERPWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event doStartCompletedEventHandler doStartCompleted;
        
        /// <remarks/>
        public event doStopCompletedEventHandler doStopCompleted;
        
        /// <remarks/>
        public event doCancelCompletedEventHandler doCancelCompleted;
        
        /// <remarks/>
        public event createTravleFormCompletedEventHandler createTravleFormCompleted;
        
        /// <remarks/>
        public event getTravleAmountCompletedEventHandler getTravleAmountCompleted;
        
        /// <remarks/>
        public event getEngTravleAmountCompletedEventHandler getEngTravleAmountCompleted;
        
        /// <remarks/>
        public event openEngTravleAPEFormCompletedEventHandler openEngTravleAPEFormCompleted;
        
        /// <remarks/>
        public event openAPEFormCompletedEventHandler openAPEFormCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doStartReturn")]
        public string doStart(string empID, string AFM_NO, string CompanyID) {
            object[] results = this.Invoke("doStart", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doStartAsync(string empID, string AFM_NO, string CompanyID) {
            this.doStartAsync(empID, AFM_NO, CompanyID, null);
        }
        
        /// <remarks/>
        public void doStartAsync(string empID, string AFM_NO, string CompanyID, object userState) {
            if ((this.doStartOperationCompleted == null)) {
                this.doStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoStartOperationCompleted);
            }
            this.InvokeAsync("doStart", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID}, this.doStartOperationCompleted, userState);
        }
        
        private void OndoStartOperationCompleted(object arg) {
            if ((this.doStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doStartCompleted(this, new doStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doStopReturn")]
        public string doStop(string empID, string AFM_NO, string CompanyID, string CancelMsg) {
            object[] results = this.Invoke("doStop", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID,
                        CancelMsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doStopAsync(string empID, string AFM_NO, string CompanyID, string CancelMsg) {
            this.doStopAsync(empID, AFM_NO, CompanyID, CancelMsg, null);
        }
        
        /// <remarks/>
        public void doStopAsync(string empID, string AFM_NO, string CompanyID, string CancelMsg, object userState) {
            if ((this.doStopOperationCompleted == null)) {
                this.doStopOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoStopOperationCompleted);
            }
            this.InvokeAsync("doStop", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID,
                        CancelMsg}, this.doStopOperationCompleted, userState);
        }
        
        private void OndoStopOperationCompleted(object arg) {
            if ((this.doStopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doStopCompleted(this, new doStopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doCancelReturn")]
        public string doCancel(string empID, string AFM_NO, string CompanyID, string CancelMsg) {
            object[] results = this.Invoke("doCancel", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID,
                        CancelMsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doCancelAsync(string empID, string AFM_NO, string CompanyID, string CancelMsg) {
            this.doCancelAsync(empID, AFM_NO, CompanyID, CancelMsg, null);
        }
        
        /// <remarks/>
        public void doCancelAsync(string empID, string AFM_NO, string CompanyID, string CancelMsg, object userState) {
            if ((this.doCancelOperationCompleted == null)) {
                this.doCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoCancelOperationCompleted);
            }
            this.InvokeAsync("doCancel", new object[] {
                        empID,
                        AFM_NO,
                        CompanyID,
                        CancelMsg}, this.doCancelOperationCompleted, userState);
        }
        
        private void OndoCancelOperationCompleted(object arg) {
            if ((this.doCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doCancelCompleted(this, new doCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("createTravleFormReturn")]
        public string createTravleForm(string empID, string AFM_NO) {
            object[] results = this.Invoke("createTravleForm", new object[] {
                        empID,
                        AFM_NO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createTravleFormAsync(string empID, string AFM_NO) {
            this.createTravleFormAsync(empID, AFM_NO, null);
        }
        
        /// <remarks/>
        public void createTravleFormAsync(string empID, string AFM_NO, object userState) {
            if ((this.createTravleFormOperationCompleted == null)) {
                this.createTravleFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTravleFormOperationCompleted);
            }
            this.InvokeAsync("createTravleForm", new object[] {
                        empID,
                        AFM_NO}, this.createTravleFormOperationCompleted, userState);
        }
        
        private void OncreateTravleFormOperationCompleted(object arg) {
            if ((this.createTravleFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTravleFormCompleted(this, new createTravleFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getTravleAmountReturn")]
        public string getTravleAmount(string empID, string AFM_NO) {
            object[] results = this.Invoke("getTravleAmount", new object[] {
                        empID,
                        AFM_NO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTravleAmountAsync(string empID, string AFM_NO) {
            this.getTravleAmountAsync(empID, AFM_NO, null);
        }
        
        /// <remarks/>
        public void getTravleAmountAsync(string empID, string AFM_NO, object userState) {
            if ((this.getTravleAmountOperationCompleted == null)) {
                this.getTravleAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTravleAmountOperationCompleted);
            }
            this.InvokeAsync("getTravleAmount", new object[] {
                        empID,
                        AFM_NO}, this.getTravleAmountOperationCompleted, userState);
        }
        
        private void OngetTravleAmountOperationCompleted(object arg) {
            if ((this.getTravleAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTravleAmountCompleted(this, new getTravleAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getEngTravleAmountReturn")]
        public string getEngTravleAmount(string AFM_NO) {
            object[] results = this.Invoke("getEngTravleAmount", new object[] {
                        AFM_NO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getEngTravleAmountAsync(string AFM_NO) {
            this.getEngTravleAmountAsync(AFM_NO, null);
        }
        
        /// <remarks/>
        public void getEngTravleAmountAsync(string AFM_NO, object userState) {
            if ((this.getEngTravleAmountOperationCompleted == null)) {
                this.getEngTravleAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEngTravleAmountOperationCompleted);
            }
            this.InvokeAsync("getEngTravleAmount", new object[] {
                        AFM_NO}, this.getEngTravleAmountOperationCompleted, userState);
        }
        
        private void OngetEngTravleAmountOperationCompleted(object arg) {
            if ((this.getEngTravleAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEngTravleAmountCompleted(this, new getEngTravleAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("openEngTravleAPEFormReturn")]
        public string openEngTravleAPEForm(string loginID, string AFM_NO, string comsStatus) {
            object[] results = this.Invoke("openEngTravleAPEForm", new object[] {
                        loginID,
                        AFM_NO,
                        comsStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void openEngTravleAPEFormAsync(string loginID, string AFM_NO, string comsStatus) {
            this.openEngTravleAPEFormAsync(loginID, AFM_NO, comsStatus, null);
        }
        
        /// <remarks/>
        public void openEngTravleAPEFormAsync(string loginID, string AFM_NO, string comsStatus, object userState) {
            if ((this.openEngTravleAPEFormOperationCompleted == null)) {
                this.openEngTravleAPEFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnopenEngTravleAPEFormOperationCompleted);
            }
            this.InvokeAsync("openEngTravleAPEForm", new object[] {
                        loginID,
                        AFM_NO,
                        comsStatus}, this.openEngTravleAPEFormOperationCompleted, userState);
        }
        
        private void OnopenEngTravleAPEFormOperationCompleted(object arg) {
            if ((this.openEngTravleAPEFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.openEngTravleAPEFormCompleted(this, new openEngTravleAPEFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://172.16.1.34:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("openAPEFormReturn")]
        public string openAPEForm(string empID) {
            object[] results = this.Invoke("openAPEForm", new object[] {
                        empID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void openAPEFormAsync(string empID) {
            this.openAPEFormAsync(empID, null);
        }
        
        /// <remarks/>
        public void openAPEFormAsync(string empID, object userState) {
            if ((this.openAPEFormOperationCompleted == null)) {
                this.openAPEFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnopenAPEFormOperationCompleted);
            }
            this.InvokeAsync("openAPEForm", new object[] {
                        empID}, this.openAPEFormOperationCompleted, userState);
        }
        
        private void OnopenAPEFormOperationCompleted(object arg) {
            if ((this.openAPEFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.openAPEFormCompleted(this, new openAPEFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doStartCompletedEventHandler(object sender, doStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doStopCompletedEventHandler(object sender, doStopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doStopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doStopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doCancelCompletedEventHandler(object sender, doCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void createTravleFormCompletedEventHandler(object sender, createTravleFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createTravleFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createTravleFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getTravleAmountCompletedEventHandler(object sender, getTravleAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTravleAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTravleAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getEngTravleAmountCompletedEventHandler(object sender, getEngTravleAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEngTravleAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEngTravleAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void openEngTravleAPEFormCompletedEventHandler(object sender, openEngTravleAPEFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class openEngTravleAPEFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal openEngTravleAPEFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void openAPEFormCompletedEventHandler(object sender, openAPEFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class openAPEFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal openAPEFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591