//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace Kedge.ws.EngineerBillWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EngineerBillWebKedgeSoapBinding", Namespace="http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerBillWebKedge." +
        "jws")]
    public partial class EngineerBillWebKedgeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback doStartOperationCompleted;
        
        private System.Threading.SendOrPostCallback doStopOperationCompleted;
        
        private System.Threading.SendOrPostCallback doStartURLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EngineerBillWebKedgeService() {
            this.Url = global::Kedge.ws.Properties.Settings.Default.KedgeWebService_EngineerBillWeb_EngineerBillWebKedgeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event doStartCompletedEventHandler doStartCompleted;
        
        /// <remarks/>
        public event doStopCompletedEventHandler doStopCompleted;
        
        /// <remarks/>
        public event doStartURLCompletedEventHandler doStartURLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerBillWebKedge." +
            "jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doStartReturn")]
        public string doStart(string memId, string accUid) {
            object[] results = this.Invoke("doStart", new object[] {
                        memId,
                        accUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doStartAsync(string memId, string accUid) {
            this.doStartAsync(memId, accUid, null);
        }
        
        /// <remarks/>
        public void doStartAsync(string memId, string accUid, object userState) {
            if ((this.doStartOperationCompleted == null)) {
                this.doStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoStartOperationCompleted);
            }
            this.InvokeAsync("doStart", new object[] {
                        memId,
                        accUid}, this.doStartOperationCompleted, userState);
        }
        
        private void OndoStartOperationCompleted(object arg) {
            if ((this.doStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doStartCompleted(this, new doStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerBillWebKedge." +
            "jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doStopReturn")]
        public string doStop(string memId, string accUid, string cancelMsg) {
            object[] results = this.Invoke("doStop", new object[] {
                        memId,
                        accUid,
                        cancelMsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doStopAsync(string memId, string accUid, string cancelMsg) {
            this.doStopAsync(memId, accUid, cancelMsg, null);
        }
        
        /// <remarks/>
        public void doStopAsync(string memId, string accUid, string cancelMsg, object userState) {
            if ((this.doStopOperationCompleted == null)) {
                this.doStopOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoStopOperationCompleted);
            }
            this.InvokeAsync("doStop", new object[] {
                        memId,
                        accUid,
                        cancelMsg}, this.doStopOperationCompleted, userState);
        }
        
        private void OndoStopOperationCompleted(object arg) {
            if ((this.doStopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doStopCompleted(this, new doStopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerBillWebKedge." +
            "jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("doStartURLReturn")]
        public string doStartURL(string memId, string accUid) {
            object[] results = this.Invoke("doStartURL", new object[] {
                        memId,
                        accUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doStartURLAsync(string memId, string accUid) {
            this.doStartURLAsync(memId, accUid, null);
        }
        
        /// <remarks/>
        public void doStartURLAsync(string memId, string accUid, object userState) {
            if ((this.doStartURLOperationCompleted == null)) {
                this.doStartURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoStartURLOperationCompleted);
            }
            this.InvokeAsync("doStartURL", new object[] {
                        memId,
                        accUid}, this.doStartURLOperationCompleted, userState);
        }
        
        private void OndoStartURLOperationCompleted(object arg) {
            if ((this.doStartURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doStartURLCompleted(this, new doStartURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doStartCompletedEventHandler(object sender, doStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doStopCompletedEventHandler(object sender, doStopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doStopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doStopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void doStartURLCompletedEventHandler(object sender, doStartURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doStartURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doStartURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591