//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kedge.ws.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://220.130.9.24:8080/WebAgenda/webservice/AgentflowWeb.jws")]
        public string KedgeWebService_AgentflowWeb_AgentflowWebService {
            get {
                return ((string)(this["KedgeWebService_AgentflowWeb_AgentflowWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerPR.jws")]
        public string KedgeWebService_EngineerPR_EngineerPRService {
            get {
                return ((string)(this["KedgeWebService_EngineerPR_EngineerPRService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerBillWebKedge." +
            "jws")]
        public string KedgeWebService_EngineerBillWeb_EngineerBillWebKedgeService {
            get {
                return ((string)(this["KedgeWebService_EngineerBillWeb_EngineerBillWebKedgeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://220.130.9.24:8080/WebAgenda/webservice/EngineerPR.jws")]
        public string KedgeWebService_EngineerPRExt_EngineerPRService {
            get {
                return ((string)(this["KedgeWebService_EngineerPRExt_EngineerPRService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://220.130.9.24:8080/WebAgenda/webservice/EngineerBillWebKedge.jws")]
        public string KedgeWebService_EngineerBillWebExt_EngineerBillWebKedgeService {
            get {
                return ((string)(this["KedgeWebService_EngineerBillWebExt_EngineerBillWebKedgeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agentflow-qa.kindom.com.tw:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        public string KedgeWebService_EngineerERPWeb_EngineerERPWebService {
            get {
                return ((string)(this["KedgeWebService_EngineerERPWeb_EngineerERPWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://220.130.9.24:8080/WebAgenda/webservice/EngineerERPWeb.jws")]
        public string KedgeWebService_EngineerERPWebExt_EngineerERPWebService {
            get {
                return ((string)(this["KedgeWebService_EngineerERPWebExt_EngineerERPWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://220.130.9.26:8080/WebAgenda/webservice/KEDGEWebService.jws")]
        public string KedgeAgentFlowWS_ExpenseClaimWeb_KEDGEWebServiceService {
            get {
                return ((string)(this["KedgeAgentFlowWS_ExpenseClaimWeb_KEDGEWebServiceService"]));
            }
        }
    }
}
